
# This file was *autogenerated* from the file a.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_0 = Integer(0)
K = GF( _sage_const_2 **_sage_const_8  , names=('a',)); (a,) = K._first_ngens(1)
E = EllipticCurve( K, [_sage_const_1 ,(_sage_const_1 ),_sage_const_0 ,_sage_const_0 ,(a**_sage_const_2 +_sage_const_1 )])
print E.abelian_group(debug=True)

